/**
 * 物件マスタの seed データ。
 *
 *   npm run db:seed
 *
 * 掲載しているのはすべて架空の物件です（実在物件のデータは使用していません）。
 * 鹿児島・福岡を中心に、家賃帯・築年数・設備がばらけるよう意図的に構成し、
 * 「重視条件を切り替えるとランキングが変わる」ことを確認できるようにしている。
 */
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface SeedProperty {
  name: string;
  prefecture: string;
  city: string;
  area: string;
  rent: number;
  managementFee: number;
  deposit: number;
  keyMoney: number;
  layout: string;
  sizeSqm: number;
  buildingAge: number;
  floor: number;
  structure: string;
  nearestLine: string;
  nearestStation: string;
  walkMinutes: number;
  hasParking: boolean;
  petAllowed: boolean;
  remoteWorkScore: number;
  internet: string;
  hasAutoLock: boolean;
  hasBathToilet: boolean;
  appealPoints: string[];
  cautionPoints: string[];
  tags: string[];
  description: string;
  image: number;
  latitude: number;
  longitude: number;
}

const RC = "鉄筋コンクリート造";
const SRC = "鉄骨鉄筋コンクリート造";
const WOOD = "木造";
const STEEL = "鉄骨造";

const properties: SeedProperty[] = [
  {
    name: "グランメゾン天文館",
    prefecture: "鹿児島県", city: "鹿児島市", area: "東千石町",
    rent: 78000, managementFee: 6000, deposit: 78000, keyMoney: 78000,
    layout: "1LDK", sizeSqm: 42.5, buildingAge: 4, floor: 8, structure: RC,
    nearestLine: "鹿児島市電", nearestStation: "天文館通", walkMinutes: 3,
    hasParking: true, petAllowed: false, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["天文館アーケードまで徒歩3分で買い物に困らない", "各室にLAN配線があり在宅ワークに対応", "オートロック・防犯カメラ完備"],
    cautionPoints: ["繁華街に近いため週末は人通りが多い"],
    tags: ["オートロック", "宅配ボックス", "独立洗面台"],
    description: "天文館エリア中心部の築浅分譲賃貸。生活利便性と在宅ワーク環境を両立した物件です。",
    image: 1, latitude: 31.5917, longitude: 130.5556,
  },
  {
    name: "リヴェール中央町",
    prefecture: "鹿児島県", city: "鹿児島市", area: "中央町",
    rent: 82000, managementFee: 5000, deposit: 164000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 45.2, buildingAge: 2, floor: 11, structure: RC,
    nearestLine: "JR鹿児島本線", nearestStation: "鹿児島中央", walkMinutes: 4,
    hasParking: true, petAllowed: true, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["鹿児島中央駅徒歩4分で新幹線通勤も可能", "小型犬・猫の飼育可（2匹まで）", "designer's仕様の広めのワークスペース"],
    cautionPoints: ["人気エリアのため家賃はやや高め"],
    tags: ["ペット可", "オートロック", "浴室乾燥機", "宅配ボックス"],
    description: "鹿児島中央駅至近のタワー型賃貸マンション。ペット可・在宅ワーク対応の希少物件。",
    image: 2, latitude: 31.5836, longitude: 130.5417,
  },
  {
    name: "パークサイド荒田",
    prefecture: "鹿児島県", city: "鹿児島市", area: "荒田",
    rent: 68000, managementFee: 4000, deposit: 68000, keyMoney: 68000,
    layout: "1LDK", sizeSqm: 40.1, buildingAge: 9, floor: 3, structure: RC,
    nearestLine: "鹿児島市電", nearestStation: "騎射場", walkMinutes: 6,
    hasParking: true, petAllowed: false, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["鹿児島大学至近で飲食店・スーパーが充実", "駐車場が敷地内に確保できる", "南向きバルコニーで日当たり良好"],
    cautionPoints: ["築9年のため水回り設備は最新ではない"],
    tags: ["駐車場あり", "オートロック", "南向き"],
    description: "騎射場エリアの落ち着いた住宅街に建つファミリー向け1LDK。",
    image: 3, latitude: 31.5709, longitude: 130.5469,
  },
  {
    name: "コンフォート宇宿",
    prefecture: "鹿児島県", city: "鹿児島市", area: "宇宿",
    rent: 62000, managementFee: 3000, deposit: 62000, keyMoney: 0,
    layout: "2LDK", sizeSqm: 52.8, buildingAge: 14, floor: 4, structure: RC,
    nearestLine: "JR指宿枕崎線", nearestStation: "宇宿", walkMinutes: 8,
    hasParking: true, petAllowed: false, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["2LDKで52.8m²と広く、書斎スペースを確保できる", "イオン鹿児島まで徒歩圏", "駐車場2台目も相談可"],
    cautionPoints: ["オートロックは非搭載", "築14年で外観に経年感あり"],
    tags: ["駐車場あり", "角部屋", "追い焚き"],
    description: "宇宿エリアの広さ重視向け2LDK。コストを抑えつつ在宅ワーク部屋を確保したい方に。",
    image: 4, latitude: 31.5507, longitude: 130.5313,
  },
  {
    name: "アルテハイム谷山",
    prefecture: "鹿児島県", city: "鹿児島市", area: "谷山中央",
    rent: 54000, managementFee: 3000, deposit: 54000, keyMoney: 54000,
    layout: "2DK", sizeSqm: 48.0, buildingAge: 22, floor: 2, structure: RC,
    nearestLine: "JR指宿枕崎線", nearestStation: "谷山", walkMinutes: 10,
    hasParking: true, petAllowed: true, remoteWorkScore: 3, internet: "光回線対応",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["家賃5.4万円で2DK・駐車場込みの高コスパ", "ペット飼育可（小型犬1匹）", "周辺にスーパー・ドラッグストアが揃う"],
    cautionPoints: ["築22年で設備の一部が旧型", "駅まで徒歩10分"],
    tags: ["ペット可", "駐車場あり", "コスパ"],
    description: "谷山中央のコストパフォーマンス重視物件。初期費用も抑えられます。",
    image: 5, latitude: 31.5108, longitude: 130.5145,
  },
  {
    name: "ルミエール城西",
    prefecture: "鹿児島県", city: "鹿児島市", area: "城西",
    rent: 71000, managementFee: 4500, deposit: 71000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 38.6, buildingAge: 6, floor: 5, structure: RC,
    nearestLine: "鹿児島市電", nearestStation: "加治屋町", walkMinutes: 7,
    hasParking: false, petAllowed: false, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["インターネット無料で通信費を削減できる", "築6年の築浅・オートロック付き", "静かな住宅街で在宅ワークに集中しやすい"],
    cautionPoints: ["敷地内に駐車場が無く近隣月極を借りる必要がある"],
    tags: ["ネット無料", "オートロック", "宅配ボックス"],
    description: "城西エリアの築浅1LDK。通信環境を重視する在宅ワーカー向け。",
    image: 6, latitude: 31.5901, longitude: 130.5455,
  },
  {
    name: "サンリット吉野",
    prefecture: "鹿児島県", city: "鹿児島市", area: "吉野町",
    rent: 58000, managementFee: 3000, deposit: 0, keyMoney: 0,
    layout: "2LDK", sizeSqm: 56.4, buildingAge: 18, floor: 3, structure: RC,
    nearestLine: "JR日豊本線", nearestStation: "竜ヶ水", walkMinutes: 22,
    hasParking: true, petAllowed: true, remoteWorkScore: 3, internet: "ADSL/光回線相談",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["敷金礼金ゼロで初期費用を大幅に抑えられる", "56.4m²の広さと駐車場2台分", "桜島を望む眺望"],
    cautionPoints: ["最寄駅まで徒歩22分でバス・車移動が前提", "光回線は要事前確認"],
    tags: ["敷金礼金ゼロ", "ペット可", "駐車場2台"],
    description: "吉野台地の眺望が魅力の広めの2LDK。車移動が中心の方向け。",
    image: 7, latitude: 31.6191, longitude: 130.5804,
  },
  {
    name: "グレイス郡元レジデンス",
    prefecture: "鹿児島県", city: "鹿児島市", area: "郡元",
    rent: 75000, managementFee: 5000, deposit: 75000, keyMoney: 75000,
    layout: "2LDK", sizeSqm: 58.2, buildingAge: 5, floor: 6, structure: RC,
    nearestLine: "鹿児島市電", nearestStation: "郡元", walkMinutes: 5,
    hasParking: true, petAllowed: false, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["築5年・58.2m²の2LDKで在宅ワーク部屋を確保できる", "市電郡元電停まで徒歩5分", "床暖房・浴室乾燥機付き"],
    cautionPoints: ["ペット飼育は不可"],
    tags: ["オートロック", "浴室乾燥機", "床暖房", "駐車場あり"],
    description: "郡元エリアの築浅ファミリー向け2LDK。設備グレードの高さが特徴です。",
    image: 8, latitude: 31.5643, longitude: 130.5459,
  },
  {
    name: "メゾン南鹿児島",
    prefecture: "鹿児島県", city: "鹿児島市", area: "南林寺町",
    rent: 49000, managementFee: 2500, deposit: 49000, keyMoney: 0,
    layout: "1DK", sizeSqm: 28.5, buildingAge: 26, floor: 2, structure: RC,
    nearestLine: "鹿児島市電", nearestStation: "南鹿児島駅前", walkMinutes: 9,
    hasParking: false, petAllowed: false, remoteWorkScore: 2, internet: "回線引込工事要",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["家賃4.9万円と市内でも屈指の低価格", "礼金ゼロ"],
    cautionPoints: ["築26年・28.5m²とコンパクト", "インターネットは自身で回線工事が必要", "駐車場なし"],
    tags: ["低価格", "礼金ゼロ"],
    description: "とにかく家賃を抑えたい単身者向けの1DK。",
    image: 9, latitude: 31.5677, longitude: 130.5407,
  },
  {
    name: "ブランノワール騎射場",
    prefecture: "鹿児島県", city: "鹿児島市", area: "上荒田町",
    rent: 88000, managementFee: 7000, deposit: 176000, keyMoney: 88000,
    layout: "2LDK", sizeSqm: 62.0, buildingAge: 1, floor: 9, structure: RC,
    nearestLine: "鹿児島市電", nearestStation: "騎射場", walkMinutes: 4,
    hasParking: true, petAllowed: true, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["築1年の新築同様物件", "62m²の2LDK＋ワークスペース設計", "ペット可・オートロック・宅配ボックス完備"],
    cautionPoints: ["家賃・初期費用ともにエリア相場より高め"],
    tags: ["築浅", "ペット可", "オートロック", "宅配ボックス", "ワークスペース"],
    description: "騎射場エリア最新の分譲賃貸。設備・立地・広さのすべてを求める方へ。",
    image: 10, latitude: 31.5721, longitude: 130.5451,
  },
  {
    name: "シティコート照国",
    prefecture: "鹿児島県", city: "鹿児島市", area: "照国町",
    rent: 66000, managementFee: 4000, deposit: 66000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 36.2, buildingAge: 11, floor: 4, structure: RC,
    nearestLine: "鹿児島市電", nearestStation: "高見馬場", walkMinutes: 5,
    hasParking: false, petAllowed: false, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["中心市街地まで徒歩圏で通勤利便性が高い", "礼金ゼロ", "オートロック付き"],
    cautionPoints: ["駐車場が無い", "36.2m²とやや手狭"],
    tags: ["礼金ゼロ", "オートロック", "駅近"],
    description: "照国神社近くの好立地1LDK。徒歩・市電中心の生活に最適。",
    image: 11, latitude: 31.5947, longitude: 130.5502,
  },
  {
    name: "ヴィラ慈眼寺",
    prefecture: "鹿児島県", city: "鹿児島市", area: "和田",
    rent: 57000, managementFee: 3000, deposit: 57000, keyMoney: 57000,
    layout: "2LDK", sizeSqm: 54.6, buildingAge: 16, floor: 2, structure: RC,
    nearestLine: "JR指宿枕崎線", nearestStation: "慈眼寺", walkMinutes: 12,
    hasParking: true, petAllowed: false, remoteWorkScore: 3, internet: "光回線対応",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["54.6m²の2LDKを6万円以下で確保できる", "慈眼寺公園が近く生活環境が良好", "駐車場込みの家賃設定"],
    cautionPoints: ["駅まで徒歩12分", "オートロックなし"],
    tags: ["駐車場あり", "コスパ", "公園近く"],
    description: "慈眼寺エリアの広さとコストのバランスに優れた2LDK。",
    image: 12, latitude: 31.5031, longitude: 130.5211,
  },
  {
    name: "リバーサイド甲突",
    prefecture: "鹿児島県", city: "鹿児島市", area: "西田",
    rent: 72000, managementFee: 4000, deposit: 72000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 44.0, buildingAge: 8, floor: 7, structure: RC,
    nearestLine: "JR鹿児島本線", nearestStation: "鹿児島中央", walkMinutes: 9,
    hasParking: true, petAllowed: true, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["甲突川沿いで眺望・環境ともに良好", "ペット可かつ駐車場あり", "鹿児島中央駅まで徒歩9分"],
    cautionPoints: ["川沿いのため夏場は虫が出やすい"],
    tags: ["ペット可", "駐車場あり", "オートロック"],
    description: "甲突川沿いの落ち着いた住環境。駅アクセスと生活環境を両立。",
    image: 1, latitude: 31.5871, longitude: 130.5372,
  },
  {
    name: "ステージ国分中央",
    prefecture: "鹿児島県", city: "霧島市", area: "国分中央",
    rent: 59000, managementFee: 3000, deposit: 59000, keyMoney: 0,
    layout: "2LDK", sizeSqm: 57.5, buildingAge: 7, floor: 3, structure: RC,
    nearestLine: "JR日豊本線", nearestStation: "国分", walkMinutes: 8,
    hasParking: true, petAllowed: false, remoteWorkScore: 4, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["築7年・57.5m²で家賃5.9万円と割安", "インターネット無料", "駐車場2台分を確保可能"],
    cautionPoints: ["鹿児島市中心部までは車で約50分"],
    tags: ["ネット無料", "駐車場2台", "築浅"],
    description: "霧島市国分の中心部。広さとコストを両立したファミリー向け物件。",
    image: 2, latitude: 31.7365, longitude: 130.7627,
  },
  {
    name: "パレス隼人",
    prefecture: "鹿児島県", city: "霧島市", area: "隼人町",
    rent: 47000, managementFee: 2000, deposit: 0, keyMoney: 0,
    layout: "2DK", sizeSqm: 46.2, buildingAge: 24, floor: 2, structure: RC,
    nearestLine: "JR日豊本線", nearestStation: "隼人", walkMinutes: 11,
    hasParking: true, petAllowed: true, remoteWorkScore: 2, internet: "回線引込工事要",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["敷金礼金ゼロ・家賃4.7万円と初期費用が最小限", "ペット可", "駐車場無料"],
    cautionPoints: ["築24年で設備は旧型", "インターネットは回線工事が必要"],
    tags: ["敷金礼金ゼロ", "ペット可", "低価格"],
    description: "隼人エリアのコスト最優先物件。車移動が中心の方向け。",
    image: 3, latitude: 31.7422, longitude: 130.7358,
  },
  {
    name: "サンクレール姶良",
    prefecture: "鹿児島県", city: "姶良市", area: "西餅田",
    rent: 63000, managementFee: 3500, deposit: 63000, keyMoney: 63000,
    layout: "3LDK", sizeSqm: 70.5, buildingAge: 12, floor: 2, structure: RC,
    nearestLine: "JR日豊本線", nearestStation: "帖佐", walkMinutes: 14,
    hasParking: true, petAllowed: false, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["70.5m²の3LDKで独立した仕事部屋を確保できる", "駐車場2台込みの家賃", "大型商業施設が徒歩圏"],
    cautionPoints: ["駅まで徒歩14分", "オートロックなし"],
    tags: ["3LDK", "駐車場2台", "広さ重視"],
    description: "姶良市の広々3LDK。在宅ワーク部屋と家族スペースを分けたい方に。",
    image: 4, latitude: 31.7286, longitude: 130.6294,
  },
  {
    name: "エクセレント薬院",
    prefecture: "福岡県", city: "福岡市中央区", area: "薬院",
    rent: 98000, managementFee: 8000, deposit: 98000, keyMoney: 98000,
    layout: "1LDK", sizeSqm: 41.8, buildingAge: 3, floor: 10, structure: RC,
    nearestLine: "西鉄天神大牟田線", nearestStation: "薬院", walkMinutes: 3,
    hasParking: false, petAllowed: true, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["薬院駅徒歩3分・天神まで1駅の一等地", "築3年でペット飼育可", "ネット無料・宅配ボックス完備"],
    cautionPoints: ["駐車場が無く車所有には不向き", "家賃は市内でも高水準"],
    tags: ["駅近", "ペット可", "ネット無料", "オートロック"],
    description: "福岡市中心部・薬院の築浅デザイナーズ1LDK。",
    image: 5, latitude: 33.5806, longitude: 130.4014,
  },
  {
    name: "アーバンレジデンス大濠",
    prefecture: "福岡県", city: "福岡市中央区", area: "大濠",
    rent: 125000, managementFee: 10000, deposit: 250000, keyMoney: 125000,
    layout: "2LDK", sizeSqm: 64.3, buildingAge: 6, floor: 12, structure: SRC,
    nearestLine: "福岡市地下鉄空港線", nearestStation: "大濠公園", walkMinutes: 5,
    hasParking: true, petAllowed: true, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["大濠公園徒歩5分の住環境", "64.3m²の2LDK・機械式駐車場あり", "コンシェルジュサービス付き"],
    cautionPoints: ["家賃・初期費用ともに高額"],
    tags: ["高級", "ペット可", "駐車場あり", "オートロック"],
    description: "大濠公園至近のハイグレード2LDK。住環境を最優先する方へ。",
    image: 6, latitude: 33.5872, longitude: 130.3798,
  },
  {
    name: "プレミア博多駅東",
    prefecture: "福岡県", city: "福岡市博多区", area: "博多駅東",
    rent: 89000, managementFee: 7000, deposit: 89000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 39.5, buildingAge: 5, floor: 8, structure: RC,
    nearestLine: "JR鹿児島本線", nearestStation: "博多", walkMinutes: 6,
    hasParking: false, petAllowed: false, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["博多駅徒歩6分で出張・通勤に最適", "礼金ゼロ", "在宅ワーク用のカウンターデスク造作済み"],
    cautionPoints: ["駐車場なし", "39.5m²とやや手狭"],
    tags: ["駅近", "礼金ゼロ", "ワークスペース", "オートロック"],
    description: "博多駅至近のビジネス利便性重視物件。",
    image: 7, latitude: 33.5898, longitude: 130.4234,
  },
  {
    name: "コート六本松",
    prefecture: "福岡県", city: "福岡市中央区", area: "六本松",
    rent: 84000, managementFee: 6000, deposit: 84000, keyMoney: 84000,
    layout: "2LDK", sizeSqm: 55.0, buildingAge: 10, floor: 4, structure: RC,
    nearestLine: "福岡市地下鉄七隈線", nearestStation: "六本松", walkMinutes: 7,
    hasParking: true, petAllowed: false, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["六本松421など商業施設が充実", "55m²の2LDKで駐車場あり", "天神まで地下鉄で約6分"],
    cautionPoints: ["築10年で内装に経年感あり"],
    tags: ["駐車場あり", "オートロック", "商業施設充実"],
    description: "再開発が進む六本松エリアのファミリー向け2LDK。",
    image: 8, latitude: 33.5793, longitude: 130.3821,
  },
  {
    name: "ソレイユ平尾",
    prefecture: "福岡県", city: "福岡市中央区", area: "平尾",
    rent: 76000, managementFee: 5000, deposit: 76000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 37.4, buildingAge: 13, floor: 3, structure: RC,
    nearestLine: "西鉄天神大牟田線", nearestStation: "平尾", walkMinutes: 8,
    hasParking: false, petAllowed: true, remoteWorkScore: 3, internet: "光回線対応",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["ペット飼育可（猫2匹まで）", "礼金ゼロ", "落ち着いた住宅街"],
    cautionPoints: ["築13年・オートロックなし", "駐車場なし"],
    tags: ["ペット可", "礼金ゼロ"],
    description: "平尾の閑静な住宅街に建つペット可1LDK。",
    image: 9, latitude: 33.5729, longitude: 130.4034,
  },
  {
    name: "グランドヒルズ姪浜",
    prefecture: "福岡県", city: "福岡市西区", area: "姪の浜",
    rent: 79000, managementFee: 5000, deposit: 79000, keyMoney: 79000,
    layout: "3LDK", sizeSqm: 72.0, buildingAge: 15, floor: 5, structure: RC,
    nearestLine: "福岡市地下鉄空港線", nearestStation: "姪浜", walkMinutes: 10,
    hasParking: true, petAllowed: false, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["72m²の3LDKを8万円以下で確保できる", "駐車場あり・海が近い住環境", "地下鉄で天神まで直通"],
    cautionPoints: ["築15年", "駅まで徒歩10分"],
    tags: ["3LDK", "駐車場あり", "広さ重視", "オートロック"],
    description: "姪浜エリアの広さ重視3LDK。ファミリー・在宅ワーク併用に最適。",
    image: 10, latitude: 33.5836, longitude: 130.3211,
  },
  {
    name: "リエット香椎",
    prefecture: "福岡県", city: "福岡市東区", area: "香椎",
    rent: 65000, managementFee: 4000, deposit: 0, keyMoney: 0,
    layout: "2LDK", sizeSqm: 53.8, buildingAge: 19, floor: 3, structure: RC,
    nearestLine: "JR鹿児島本線", nearestStation: "香椎", walkMinutes: 9,
    hasParking: true, petAllowed: true, remoteWorkScore: 3, internet: "光回線対応",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["敷金礼金ゼロで初期費用を抑えられる", "ペット可・駐車場あり", "博多まで電車で約12分"],
    cautionPoints: ["築19年で共用部に経年感あり", "オートロックなし"],
    tags: ["敷金礼金ゼロ", "ペット可", "駐車場あり"],
    description: "香椎エリアのコスト重視2LDK。通勤利便性も確保。",
    image: 11, latitude: 33.6553, longitude: 130.4448,
  },
  {
    name: "アビタシオン西新",
    prefecture: "福岡県", city: "福岡市早良区", area: "西新",
    rent: 92000, managementFee: 7000, deposit: 92000, keyMoney: 92000,
    layout: "2LDK", sizeSqm: 58.6, buildingAge: 2, floor: 7, structure: RC,
    nearestLine: "福岡市地下鉄空港線", nearestStation: "西新", walkMinutes: 4,
    hasParking: false, petAllowed: false, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["築2年の新築同様物件", "西新駅徒歩4分・商店街が近い", "全居室にLAN・防音サッシ採用"],
    cautionPoints: ["駐車場が無い", "家賃はエリア相場より高め"],
    tags: ["築浅", "駅近", "ネット無料", "オートロック"],
    description: "西新エリアの築浅ハイグレード2LDK。在宅ワーク環境が充実。",
    image: 12, latitude: 33.5817, longitude: 130.3577,
  },
  {
    name: "メイプル百道",
    prefecture: "福岡県", city: "福岡市早良区", area: "百道",
    rent: 105000, managementFee: 8000, deposit: 210000, keyMoney: 105000,
    layout: "3LDK", sizeSqm: 76.4, buildingAge: 9, floor: 9, structure: RC,
    nearestLine: "福岡市地下鉄空港線", nearestStation: "藤崎", walkMinutes: 11,
    hasParking: true, petAllowed: true, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["76.4m²の3LDKで書斎を確保できる", "ペット可・駐車場あり", "百道浜の良好な住環境"],
    cautionPoints: ["家賃10万円超と高額", "駅まで徒歩11分"],
    tags: ["3LDK", "ペット可", "駐車場あり", "高級"],
    description: "百道エリアのファミリー向けハイグレード3LDK。",
    image: 1, latitude: 33.5893, longitude: 130.3517,
  },
  {
    name: "サンフラット小倉北",
    prefecture: "福岡県", city: "北九州市小倉北区", area: "浅野",
    rent: 61000, managementFee: 4000, deposit: 61000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 40.8, buildingAge: 8, floor: 6, structure: RC,
    nearestLine: "JR鹿児島本線", nearestStation: "小倉", walkMinutes: 5,
    hasParking: true, petAllowed: false, remoteWorkScore: 4, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["小倉駅徒歩5分で6万円台の好条件", "インターネット無料", "駐車場を敷地内に確保"],
    cautionPoints: ["ペット不可"],
    tags: ["駅近", "ネット無料", "駐車場あり", "オートロック"],
    description: "小倉駅至近の好条件1LDK。コストと立地のバランスに優れます。",
    image: 2, latitude: 33.8873, longitude: 130.8823,
  },
  {
    name: "パークホームズ黒崎",
    prefecture: "福岡県", city: "北九州市八幡西区", area: "黒崎",
    rent: 52000, managementFee: 3000, deposit: 52000, keyMoney: 52000,
    layout: "2LDK", sizeSqm: 51.2, buildingAge: 21, floor: 4, structure: RC,
    nearestLine: "JR鹿児島本線", nearestStation: "黒崎", walkMinutes: 12,
    hasParking: true, petAllowed: true, remoteWorkScore: 2, internet: "回線引込工事要",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["家賃5.2万円で2LDK・駐車場付き", "ペット飼育可"],
    cautionPoints: ["築21年", "インターネットは回線工事が必要", "駅まで徒歩12分"],
    tags: ["ペット可", "駐車場あり", "低価格"],
    description: "黒崎エリアのコスト最優先2LDK。",
    image: 3, latitude: 33.8617, longitude: 130.7639,
  },
  {
    name: "ノースコート箱崎",
    prefecture: "福岡県", city: "福岡市東区", area: "箱崎",
    rent: 71000, managementFee: 4500, deposit: 71000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 43.2, buildingAge: 4, floor: 5, structure: RC,
    nearestLine: "福岡市地下鉄箱崎線", nearestStation: "箱崎宮前", walkMinutes: 6,
    hasParking: true, petAllowed: false, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["築4年・43.2m²で7万円台", "ネット無料・宅配ボックス完備", "駐車場を確保できる"],
    cautionPoints: ["ペット不可"],
    tags: ["築浅", "ネット無料", "駐車場あり", "オートロック"],
    description: "箱崎エリアの築浅1LDK。在宅ワークと通勤の両立に適した物件。",
    image: 4, latitude: 33.6144, longitude: 130.4239,
  },
  {
    name: "アルコバレーノ天神南",
    prefecture: "福岡県", city: "福岡市中央区", area: "渡辺通",
    rent: 112000, managementFee: 9000, deposit: 112000, keyMoney: 112000,
    layout: "2LDK", sizeSqm: 60.5, buildingAge: 1, floor: 14, structure: RC,
    nearestLine: "福岡市地下鉄七隈線", nearestStation: "天神南", walkMinutes: 4,
    hasParking: true, petAllowed: true, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["築1年・天神南駅徒歩4分の最上級立地", "ペット可・駐車場あり", "全室ワークスペース設計"],
    cautionPoints: ["家賃11万円超と高額", "初期費用も高い"],
    tags: ["築浅", "駅近", "ペット可", "高級", "オートロック"],
    description: "天神南の新築タワー型2LDK。立地・設備ともに最高水準。",
    image: 5, latitude: 33.5859, longitude: 130.4041,
  },
  {
    name: "セジュール大橋",
    prefecture: "福岡県", city: "福岡市南区", area: "大橋",
    rent: 69000, managementFee: 4000, deposit: 69000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 38.0, buildingAge: 12, floor: 3, structure: RC,
    nearestLine: "西鉄天神大牟田線", nearestStation: "大橋", walkMinutes: 7,
    hasParking: false, petAllowed: false, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["大橋駅徒歩7分・天神まで急行7分", "礼金ゼロ", "オートロック付き"],
    cautionPoints: ["駐車場なし", "38m²とやや手狭"],
    tags: ["駅近", "礼金ゼロ", "オートロック"],
    description: "大橋エリアの通勤利便性重視物件。",
    image: 6, latitude: 33.5539, longitude: 130.4256,
  },
  {
    name: "ラフィネ通町筋",
    prefecture: "熊本県", city: "熊本市中央区", area: "上通町",
    rent: 73000, managementFee: 5000, deposit: 73000, keyMoney: 73000,
    layout: "1LDK", sizeSqm: 41.0, buildingAge: 6, floor: 7, structure: RC,
    nearestLine: "熊本市電", nearestStation: "通町筋", walkMinutes: 3,
    hasParking: false, petAllowed: false, remoteWorkScore: 5, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["熊本市中心部の一等地で徒歩3分", "ネット無料・築6年", "商業施設が徒歩圏に集中"],
    cautionPoints: ["駐車場なし"],
    tags: ["駅近", "ネット無料", "オートロック"],
    description: "熊本市中心市街地の利便性重視1LDK。",
    image: 7, latitude: 32.8032, longitude: 130.7089,
  },
  {
    name: "グリーンコート水前寺",
    prefecture: "熊本県", city: "熊本市中央区", area: "水前寺",
    rent: 64000, managementFee: 3500, deposit: 64000, keyMoney: 0,
    layout: "2LDK", sizeSqm: 56.0, buildingAge: 13, floor: 4, structure: RC,
    nearestLine: "JR豊肥本線", nearestStation: "水前寺", walkMinutes: 9,
    hasParking: true, petAllowed: true, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["56m²の2LDKで駐車場・ペット可", "水前寺公園が徒歩圏", "礼金ゼロ"],
    cautionPoints: ["築13年"],
    tags: ["ペット可", "駐車場あり", "礼金ゼロ", "公園近く"],
    description: "水前寺エリアの住環境重視2LDK。",
    image: 8, latitude: 32.7896, longitude: 130.7385,
  },
  {
    name: "ソラーレ宮崎駅前",
    prefecture: "宮崎県", city: "宮崎市", area: "橘通東",
    rent: 56000, managementFee: 3000, deposit: 56000, keyMoney: 0,
    layout: "1LDK", sizeSqm: 39.8, buildingAge: 7, floor: 5, structure: RC,
    nearestLine: "JR日豊本線", nearestStation: "宮崎", walkMinutes: 6,
    hasParking: true, petAllowed: false, remoteWorkScore: 4, internet: "全戸光回線無料",
    hasAutoLock: true, hasBathToilet: true,
    appealPoints: ["宮崎駅徒歩6分で5万円台", "ネット無料・駐車場あり", "築7年で設備が新しい"],
    cautionPoints: ["ペット不可"],
    tags: ["駅近", "ネット無料", "駐車場あり", "オートロック"],
    description: "宮崎駅前の好条件1LDK。コストパフォーマンスに優れます。",
    image: 9, latitude: 31.9186, longitude: 131.4267,
  },
  {
    name: "メゾンドソレイユ南宮崎",
    prefecture: "宮崎県", city: "宮崎市", area: "大和町",
    rent: 48000, managementFee: 2500, deposit: 0, keyMoney: 0,
    layout: "2DK", sizeSqm: 45.5, buildingAge: 20, floor: 2, structure: STEEL,
    nearestLine: "JR日豊本線", nearestStation: "南宮崎", walkMinutes: 13,
    hasParking: true, petAllowed: true, remoteWorkScore: 2, internet: "光回線対応",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["敷金礼金ゼロ・家賃4.8万円", "ペット可・駐車場無料"],
    cautionPoints: ["築20年・鉄骨造で遮音性は標準的", "駅まで徒歩13分"],
    tags: ["敷金礼金ゼロ", "ペット可", "低価格"],
    description: "南宮崎エリアの初期費用最小物件。",
    image: 10, latitude: 31.8961, longitude: 131.4189,
  },
  {
    name: "コーポ吉野町",
    prefecture: "鹿児島県", city: "鹿児島市", area: "吉野",
    rent: 43000, managementFee: 2000, deposit: 43000, keyMoney: 0,
    layout: "1K", sizeSqm: 24.0, buildingAge: 28, floor: 1, structure: WOOD,
    nearestLine: "JR日豊本線", nearestStation: "竜ヶ水", walkMinutes: 25,
    hasParking: true, petAllowed: false, remoteWorkScore: 1, internet: "回線引込工事要",
    hasAutoLock: false, hasBathToilet: false,
    appealPoints: ["家賃4.3万円で駐車場込み"],
    cautionPoints: ["築28年・木造で24m²と手狭", "バス・トイレ一体型", "駅まで徒歩25分", "ネット環境は要工事"],
    tags: ["低価格", "駐車場あり"],
    description: "とにかく費用を抑えたい方向けの単身用物件。",
    image: 11, latitude: 31.6244, longitude: 130.5872,
  },
  {
    name: "テラス紫原",
    prefecture: "鹿児島県", city: "鹿児島市", area: "紫原",
    rent: 67000, managementFee: 4000, deposit: 67000, keyMoney: 67000,
    layout: "3LDK", sizeSqm: 68.0, buildingAge: 17, floor: 3, structure: RC,
    nearestLine: "鹿児島市電", nearestStation: "南鹿児島駅前", walkMinutes: 16,
    hasParking: true, petAllowed: false, remoteWorkScore: 4, internet: "光回線対応",
    hasAutoLock: false, hasBathToilet: true,
    appealPoints: ["68m²の3LDKで独立した仕事部屋を確保できる", "駐車場2台分あり", "紫原の落ち着いた住宅街"],
    cautionPoints: ["最寄電停まで徒歩16分", "築17年"],
    tags: ["3LDK", "駐車場2台", "広さ重視"],
    description: "紫原の高台に建つ広めの3LDK。家族向け・在宅ワーク併用に。",
    image: 12, latitude: 31.5588, longitude: 130.5389,
  },
];

async function main() {
  console.log(`seeding ${properties.length} properties...`);

  // 冪等に実行できるよう既存データを削除してから投入する
  await prisma.property.deleteMany();

  await prisma.property.createMany({
    data: properties.map((p) => ({
      name: p.name,
      prefecture: p.prefecture,
      city: p.city,
      area: p.area,
      rent: p.rent,
      managementFee: p.managementFee,
      deposit: p.deposit,
      keyMoney: p.keyMoney,
      layout: p.layout,
      sizeSqm: p.sizeSqm,
      buildingAge: p.buildingAge,
      floor: p.floor,
      structure: p.structure,
      nearestLine: p.nearestLine,
      nearestStation: p.nearestStation,
      walkMinutes: p.walkMinutes,
      hasParking: p.hasParking,
      petAllowed: p.petAllowed,
      remoteWorkScore: p.remoteWorkScore,
      internet: p.internet,
      hasAutoLock: p.hasAutoLock,
      hasBathToilet: p.hasBathToilet,
      // 配列は DB 非依存に保つため JSON 文字列として保存する
      appealPoints: JSON.stringify(p.appealPoints),
      cautionPoints: JSON.stringify(p.cautionPoints),
      tags: JSON.stringify(p.tags),
      description: p.description,
      imageUrl: `/images/properties/property-${String(p.image).padStart(2, "0")}.svg`,
      latitude: p.latitude,
      longitude: p.longitude,
      isPublished: true,
    })),
  });

  const count = await prisma.property.count();
  console.log(`done. ${count} properties in database.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
